version: '3.7'

services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redislorediscal
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379

volumes:
  redis_data:
